In [2]:
import torch
import torch.distributions as dist

D Tensor: A single number (a scalar). Example: 5
1D Tensor: A list of numbers (a vector). Example: [1, 2, 3]
2D Tensor: A grid/table of numbers (a matrix). Example: [[1, 2], [3, 4]]
3D+ Tensor: A "cube" or higher-dimensional stack of matrices.

In [3]:
torch.tensor([0.5])

tensor([0.5000])

In [4]:
# Lets create a Bernoulli distribution

bernoulli = dist.Bernoulli(torch.tensor([0.5]))

# Sample from the distribution
for _ in range(10):
    print(bernoulli.sample())

tensor([1.])
tensor([0.])
tensor([0.])
tensor([1.])
tensor([1.])
tensor([1.])
tensor([0.])
tensor([1.])
tensor([0.])
tensor([1.])


In [5]:
samples = [bernoulli.sample() for _ in range(1000)]
print(f"Mean: {torch.mean(torch.stack(samples))}")
print(f"Variance: {torch.var(torch.stack(samples))}")

Mean: 0.4659999907016754
Variance: 0.24909310042858124


In [4]:
# Lets create a Normal distribution
normal = dist.Normal(torch.tensor([0.0]), torch.tensor([1.0]))
for _ in range(10):
    print(normal.sample())

tensor([2.1612])
tensor([-0.1626])
tensor([0.4362])
tensor([-1.1543])
tensor([-0.9530])
tensor([-0.1937])
tensor([-0.0348])
tensor([0.8044])
tensor([0.3971])
tensor([0.6400])


In [ ]:
samples = [normal.sample() for _ in range(1000)]
print(f"Mean: {torch.mean(torch.stack(samples))}")
print(f"Variance: {torch.var(torch.stack(samples))}")